#
# Sample configuration file for tnexus
#

[global]
bufsize = 1048576
#apicert = <base64_cert>

[[listen]]
name = "ssh"
endpoint = "127.0.0.1:6665"
destination = "127.0.0.1:22"

[[listen]]
name = "tls"
endpoint = "127.0.0.1:6666"
sni_missing = "127.0.0.1:443"
sni_mismatch = "127.0.0.1:443"

#whether API requests are allowed on this endpoint
api = false

multiplex = { "www.redhat.com" = "23.45.109.223:443", "news.ycombinator.com" = "198.41.191.47:443" }
